---
version: "2.0"

services:
  web:
    image: chentex/random-logger
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    env:
      - TEST=test

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 16Mi
        storage:
          size: 128Mi
  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
