---
version: "2.0"

services:
  web:
    image: crccheck/hello-world
    expose:
      - port: 8000
        as: 8000
        to:
          - global: true
    env:
      - TEST=test

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 16Mi
        storage:
          size: 128Mi
  placement:
    westcoast:
      attributes:
        region: canada
      pricing:
        web:
          denom: USDTT
          amount: 1

deployment:
  web:
    westcoast:
      profile: web
      count: 1
